INSERT INTO users(email, phone, first_name, middle_name, last_name, password) values ('teacher1@mail.com', '11-11-11', 'teacher', 'иванович', 'teacher', '111');
INSERT INTO users(email, phone, first_name, middle_name, last_name, password) values ('student1@mail.com', '22-22-22', 'student1', 'иванович', 'student', '222');
INSERT INTO users(email, phone, first_name, middle_name, last_name, password) values ('student2@mail.com', '33-33-33', 'student2', 'иванович', 'student', '333');
INSERT INTO users(email, phone, first_name, middle_name, last_name, password) values ('teacher2@mail.com', '12-12-12', 'teacher2', 'иванович', 'teacher', '112');
INSERT INTO users(email, phone, first_name, middle_name, last_name, password) values ('student4@mail.com', '44-44-44', 'student3', 'иванович', 'student', '444');
INSERT INTO users(email, phone, first_name, middle_name, last_name, password) values ('student5@mail.com', '55-55-55', 'student4', 'иванович', 'student', '444');
INSERT INTO users_roles (user_id, role_id) VALUES (1, 2);
INSERT INTO users_roles (user_id, role_id) VALUES (2, 4);
INSERT INTO users_roles (user_id, role_id) VALUES (3, 4);
INSERT INTO users_roles (user_id, role_id) VALUES (4, 2);
INSERT INTO users_roles (user_id, role_id) VALUES (5, 4);
INSERT INTO users_roles (user_id, role_id) VALUES (6, 4);

INSERT INTO teachers_disciplines (teacher_id, discipline_id) VALUES (1, 6);
INSERT INTO teachers_disciplines (teacher_id, discipline_id) VALUES (4, 1);
INSERT INTO teachers_students (teacher_id, student_id, archive, dt_create, dt_modify) VALUES (1, 2, 0, DEFAULT, DEFAULT);
INSERT INTO teachers_students (teacher_id, student_id, archive, dt_create, dt_modify) VALUES (2, 2, 0, DEFAULT, DEFAULT);
INSERT INTO teachers_students (teacher_id, student_id, archive, dt_create, dt_modify) VALUES (1, 4, 0, DEFAULT, DEFAULT);
INSERT INTO teachers_students (teacher_id, student_id, archive, dt_create, dt_modify) VALUES (2, 4, 0, DEFAULT, DEFAULT);
INSERT INTO teachers_students (teacher_id, student_id, archive, dt_create, dt_modify) VALUES (5, 4, 0, DEFAULT, DEFAULT);
INSERT INTO teachers_students (teacher_id, student_id, archive, dt_create, dt_modify) VALUES (6, 4, 0, DEFAULT, DEFAULT);
INSERT INTO exercises (name, is_personal, duration, quantity, teacher_id, discipline_id) VALUES (' Английский язык ч.1', 1, 45, 4, 1, 1);
INSERT INTO exercises (name, is_personal, duration, quantity, teacher_id, discipline_id) VALUES (' Английский язык ч.2', 1, 45, 4, 1, 1);
INSERT INTO exercises (name, is_personal, duration, quantity, teacher_id, discipline_id) VALUES (' Физика ч.1', 1, 45, 4, 4, 1);
INSERT INTO exercises (name, is_personal, duration, quantity, teacher_id, discipline_id) VALUES (' Физика ч.2', 1, 45, 4, 4, 1);
INSERT INTO lessons (name, link, exercise_id, dt_start) VALUES ('урок 1', 'youtube.com/1', 1, '2022-02-12 19:30:00');
INSERT INTO lessons (name, link, exercise_id, dt_start) VALUES ('урок 2', 'youtube.com/2', 1, '2022-02-13 19:00:00');
INSERT INTO lessons (name, link, exercise_id, dt_start) VALUES ('урок 3', 'youtube.com/3', 1, '2022-02-14 18:30:00');
INSERT INTO lessons (name, link, exercise_id, dt_start) VALUES ('урок 4', 'youtube.com/4', 1, '2022-02-15 20:30:00');
INSERT INTO lessons (name, link, exercise_id, dt_start) VALUES ('урок 1', 'youtube.com/1', 2, '2022-02-12 19:30:00');
INSERT INTO lessons (name, link, exercise_id, dt_start) VALUES ('урок 2', 'youtube.com/2', 2, '2022-02-13 19:00:00');
INSERT INTO lessons (name, link, exercise_id, dt_start) VALUES ('урок 3', 'youtube.com/3', 2, '2022-02-14 18:30:00');
INSERT INTO lessons (name, link, exercise_id, dt_start) VALUES ('урок 4', 'youtube.com/4', 2, '2022-02-15 20:30:00');
INSERT INTO lessons (name, link, exercise_id, dt_start) VALUES ('урок 1', 'youtube.com/4', 3, '2022-02-15 20:30:00');
INSERT INTO lessons (name, link, exercise_id, dt_start) VALUES ('урок 2', 'youtube.com/4', 3, '2022-02-15 20:30:00');
INSERT INTO lessons (name, link, exercise_id, dt_start) VALUES ('урок 3', 'youtube.com/4', 3, '2022-02-15 20:30:00');
INSERT INTO lessons (name, link, exercise_id, dt_start) VALUES ('урок 4', 'youtube.com/4', 3, '2022-02-15 20:30:00');
INSERT INTO lessons (name, link, exercise_id, dt_start) VALUES ('урок 1', 'youtube.com/4', 4, '2022-02-15 20:30:00');
INSERT INTO lessons (name, link, exercise_id, dt_start) VALUES ('урок 2', 'youtube.com/4', 4, '2022-02-15 20:30:00');
INSERT INTO lessons (name, link, exercise_id, dt_start) VALUES ('урок 3', 'youtube.com/4', 4, '2022-02-15 20:30:00');
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (1, 2, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (2, 2, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (3, 2, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (4, 2, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (5, 2, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (6, 2, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (1, 3, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (2, 3, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (5, 3, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (6, 3, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (7, 3, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (8, 3, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (9, 3, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (10, 3, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (11, 3, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (12, 3, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (9, 5, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (10, 5, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (11, 5, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (12, 5, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (12, 2, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (13, 2, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (14, 2, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (15, 2, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (12, 6, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (13, 6, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (14, 6, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO lessons_students (lesson_id, student_id, is_attend, dt_create, dt_modify) VALUES (15, 6, DEFAULT, DEFAULT, DEFAULT);
