server:
  port: ${PORT:8189}
  servlet:
    context-path: /sh


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-170-212-187.eu-west-1.compute.amazonaws.com:5432/dcfq9v2dlv3fhi
    username: pruuhbqgbdzdmm
    password: 45711699fd20b60ee2e85f845493cd1a43bde2d55c50dc7d4878b31b0a4e3247

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        ddl-auto: validate

  # spprtscheduler@gmail.com
  # iRIIYtpu6e1&
  mail:
    host: smtp.gmail.com
    #    host: smtp.mail.ru
    port: 587
    #    port: 465
    username: spprtscheduler@gmail.com
    # spprtscheduler
    #    username: scheduler@internet.ru
    password: cxlqdyrubemqswzn
    # cxlqdyrubemqswzn
    #    password: WmfjcKa8aSvYvkhQBm0H
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          auth: true
          starttls:
            enable: true

mail:
  name:
#  name: schedulerfreeapp@gmail.com
  # spprtscheduler@gmail.com
  #  name: scheduler@internet.ru
  debug: false

app:
  debug: true

# определение файла для логирования при запуске
#$ java -Dlogging.file=/home/scheduler/app/logs/app.log -jar scheduler-0.0.1-SNAPSHOT.jar
logging:
  level:
    ru:
      team:
        scheduler:
          oapi: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logFile.log

# Секретный ключ приложения и время жизни
jwt:
  secret: 45T47fcXazP5pgMmWXKByCZWpWUzQrZrJMVegYVbcxhXFk22uVDWS9TAzpwmq8ZG
  ttl: 3600