server:
  port: 8189
  servlet:
    context-path: /scheduler

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scheduler?&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update